[package]
name = "blink"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m-rt = "0.7"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[features]
atmega328p = []
cortex_m7 = []
